stages:
  - test
  - deploy

"Testing Service":

  stage: test

  tags:
    - docker

  image: "mcr.microsoft.com/dotnet/sdk:5.0"

  script:
    - dotnet restore
    - dotnet test --configuration Release

    
"Publishing Nuget-package":

  stage: deploy

  tags:
    - docker

  image: "mcr.microsoft.com/dotnet/sdk:5.0"

  script:

    - dotnet pack -c Release

    - >
      dotnet nuget add 
      source "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/nuget/index.json" 
      --name gitlab 
      --username gitlab-ci-token 
      --password $CI_JOB_TOKEN 
      --store-password-in-clear-text

    - dotnet nuget push "bin/Release/*.nupkg" --source gitlab

  only:
    - master
